### ISSUE TITLE
ERROR undefined on nodejs 14.15

### ISSUE THREAD

**Issue by NooBiToo** [strapi/strapi-starter-nuxt-blog#27]
After updating the node from 12.x to 14.15, I cannot start the project, I tried to deploy a new project from the github, but I get the same error
```
 ERROR  undefined                                                                                                                                                                       17:26:14  

  at fn (node_modules/ky/umd.js:321:0)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Ky._retry (node_modules/ky/umd.js:412:0)
  at async HTTP.module.exports../.nuxt/http.js.HTTP.<computed> [as get] (.nuxt/http.js:92:0)
  at async asyncData (index.vue:24:0)
```

**Comment by markkaylor** [comment]
Hi @NooBiToo I just did a fresh install with node `v14.15.4` with no issues.  If you use nvm https://github.com/nvm-sh/nvm and switch back to 12.x do you still get an error?
